version: '3.1'

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=simple
      - POSTGRES_USER=simple
      - POSTGRES_PASSWORD=simple!@#
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - ./data:/var/lib/postgresql/data
