version: '3'
services:
  simple-db:
    image: postgres:11
    container_name: simple-db
    environment:
      - POSTGRES_DB=simple
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - TZ=Asia/Seoul
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
